export const petrolStationData = [
  {
    siteId: "NSC-798",
    custId: "41986",
    street: "57 Mathews Street",
    city: "Marmora",
    state: "ON",
    postal: "K0K 2M0",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Ultramar",
  },
  {
    siteId: "NSC-2184",
    custId: "50228",
    street: "91888b Alaska Hwy",
    city: "Whitehorse",
    state: "YT",
    postal: "Y1A 5B7",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Fas Gas",
  },
  {
    siteId: "NSC-2183",
    custId: "50225",
    street: "270 Alaska Hwy",
    city: "Haines Junction",
    state: "YT",
    postal: "Y0B 1L0",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Fas Gas",
  },

  // ⭐ Added 10 more sample records
  {
    siteId: "NSC-1420",
    custId: "53321",
    street: "120 King Street West",
    city: "Toronto",
    state: "ON",
    postal: "M5X 1A9",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Ultramar",
  },
  {
    siteId: "NSC-1735",
    custId: "54112",
    street: "7800 Macleod Trail SE",
    city: "Calgary",
    state: "AB",
    postal: "T2H 0L9",
    country: "Canada",
    siteType: "Commercial",
    businessUnit: "Pioneer",
  },
  {
    siteId: "NSC-1862",
    custId: "55198",
    street: "2050 Lougheed Hwy",
    city: "Vancouver",
    state: "BC",
    postal: "V5M 2A1",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Ultramar",
  },
  {
    siteId: "NSC-1991",
    custId: "56442",
    street: "655 Portage Avenue",
    city: "Winnipeg",
    state: "MB",
    postal: "R3B 2G6",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Fas Gas",
  },
  {
    siteId: "NSC-2047",
    custId: "57103",
    street: "88 Bayfield Street",
    city: "Barrie",
    state: "ON",
    postal: "L4M 3A5",
    country: "Canada",
    siteType: "Commercial",
    businessUnit: "Ultramar",
  },
  {
    siteId: "NSC-2156",
    custId: "57991",
    street: "300 University Avenue",
    city: "Charlottetown",
    state: "PE",
    postal: "C1A 4L7",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Pioneer",
  },
  {
    siteId: "NSC-2267",
    custId: "58914",
    street: "420 Mountain Road",
    city: "Moncton",
    state: "NB",
    postal: "E1C 2M4",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Ultramar",
  },
  {
    siteId: "NSC-2338",
    custId: "59472",
    street: "150 Water Street",
    city: "Summerside",
    state: "PE",
    postal: "C1N 1A9",
    country: "Canada",
    siteType: "Retail",
    businessUnit: "Fas Gas",
  },
  {
    siteId: "NSC-2471",
    custId: "60314",
    street: "989 Cliffe Avenue",
    city: "Fredericton",
    state: "NB",
    postal: "E3A 6X2",
    country: "Canada",
    siteType: "Commercial",
    businessUnit: "Ultramar",
  },
];
