export const warehousesData = [
  {
    id: 1,
    siteId: "EDM-001",
    street: "6378 Roper Road",
    city: "Edmonton",
    state: "AB",
    postal: "T6B 3G6",
    country: "Canada",
    depotType: "Full Depot",
    status: "Original",
    notes: "",
  },
  {
    id: 2,
    siteId: "FTM-001",
    street: "Suite A - 170 Maclennan Cres",
    city: "Fort McMurray",
    state: "AB",
    postal: "T9H 4B6",
    country: "Canada",
    depotType: "Tech access only",
    status: "Original",
    notes: "",
  },
  {
    id: 3,
    siteId: "LET-001",
    street: "810 - 32 Street North",
    city: "Lethbridge",
    state: "AB",
    postal: "T1H 5J1",
    country: "Canada",
    depotType: "Tech access only",
    status: "Original",
    notes: "",
  },
  {
    id: 4,
    siteId: "GRA-001",
    street: "10115 – 99th Avenue",
    city: "Grande Praire",
    state: "AB",
    postal: "T8V 0S1",
    country: "Canada",
    depotType: "Tech access only",
    status: "Original",
    notes: "",
  },
  {
    id: 5,
    siteId: "YVN-001",
    street: "4701 50TH St, Fort Vermillion",
    city: "Fort Vermillion",
    state: "AB",
    postal: "T0H 1N0",
    country: "Canada",
    depotType: "NSC Depot",
    status: "Original",
    notes: "",
  },
  {
    id: 6,
    siteId: "CAL-001",
    street: "140 – 1625 100th Ave NE",
    city: "Calgary",
    state: "AB",
    postal: "T2C 5B6",
    country: "Canada",
    depotType: "Full Depot",
    status: "Original",
    notes: "",
  },
  {
    id: 7,
    siteId: "STP-001",
    street: "4814 50th Avenue",
    city: "St. Paul",
    state: "AB",
    postal: "T0A 3A0",
    country: "Canada",
    depotType: "Tech access only",
    status: "Original",
    notes: "",
  },
  {
    id: 8,
    siteId: "WHI-001",
    street: "3475 35st",
    city: "Whitecourt",
    state: "AB",
    postal: "T7S 0B5",
    country: "Canada",
    depotType: "Tech access only",
    status: "Original",
    notes: "",
  },
];
