export const SIGN_IN = "login";
export const GET_TOLOCATIONS = "drop-locations/resource?status=10100";
export const GET_FROMLOCATIONS = "depot-locations/resource?status=10100";
export const GET_FROMLOCATIONS_WAREHOUSE = "depot-locations/resource?status=10800";
export const PUT_GEO_CODE_UPDATE = "geocode-mapping";
export const GET_LOCATION_MAPPING = "location-mapping/resource";
export const POST_TOUPLOAD = "drop-location/upload";
export const POST_FROMUPLOAD = "depot-location/upload";
export const POST_DOWNLOAD = "download-report";
export const POST_TOLOCATION_TEMPLATE_DOWNLOAD = "download-report";
export const POST_FROMLOCATION_TEMPLATE_DOWNLOAD = "download-report";
export const POST_MAPPING_START = 'location-mapping'
export const LOCATION_MAPPING_PROGRESS = "ws/location-mapping";
export const POST_MAPPING_DOWNLOAD = "download-report";
